<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "127.0.0.1");
if (!defined("PJ_USER")) define("PJ_USER", "iw-user");
if (!defined("PJ_PASS")) define("PJ_PASS", "G\$RJDZ4PuLD3xLBH@iw");
if (!defined("PJ_DB")) define("PJ_DB", "iWanaTv12020");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "booking_");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/var/www/html/BookiW/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://bookiw.iwannatrip.com/");
if (!defined("PJ_SALT")) define("PJ_SALT", "K16NAUP8");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "NTc4NDY1MDYyNjM4NDQ2MTEzNTQyNDgyMzMxMjAxOTQ1MzAwOTI0NTc4MDMzNTk5OTY3Njk4NzAzNzc2MjA5MjkyMzQzMDc2NTgxMjc1MjYxNDgyODk5MDM3ODA0NzgyMTk2IDY3MzYxMjQwMTAwNjQxODkyNDcxNDQ1ODAwNjIxMzIwODc2NzkzNjkzMjMzNDczNjg1ODUzMjUyNjU4MTc2NTYzODY2OTIyMTU3ODg3ODMxNzAwNTUzODY1NTg2MjA3ODg5NCAxNTkxNTg2NDI4MDU4MjM4MTYxNDk5ODA0MjA2MDk2NTc0MDMyNDcwMzUxNDQ1MDE3MTY1MzUyMzc1NDEzMzQxMTA5MTk2OTQ1MDI5NDc2NDczMTg3NjIxNDc5ODU1NzE2OTQgNDQ3NDU5MjcwMzMxNzAzMzk2NTE2NjA2MzI1NjkxNDIzMDk0ODYwNjY1MDU0MTExMDY5MTUxMTExMjAwMzUzMTMxMzY3MjM5NzQ1MzM5NzkwMjUzMjQ5MzE5MjIxMzgxMzAxIDEzMTk3OTE1NTUyMDA2NDkzMjcwMTE5MzM0MTc4Njc5NzY2Mjg1NzE1OTUwNDU5NjE2NzM3OTA5Mjc0MjE1ODE2MTE0NTUxNTcyMjU3OTAwODM5NTQ1NjU4MjA4MjczMzA2ODggODkxNDE3NDA1NTc3OTUyMTQwMzg0OTU1NTg1NTc2ODQ4MzM3Nzc2MjQyNTUyODI3MTkyMDUwNzc1OTExMTM3Mzk2NDY2NzkxMjU2NjIzODcxMjgyMTczMTg4NTIxNjEzMTcgMTYzNTIzNzM4OTAxNzkxNTYzOTE3MTgwNjU4NDU0NTI1MDkyNjg1NTY0OTcyMjI4NDk3OTk0MzI0ODE4MDM4NDI4NjY2Mjk0OTg5NDA2NzM0Mjc3MjM1NjAzMTg2ODQxMTMw");
?>